parameters:
  planets:

    MARTE:
      name: Marte
      length: 100
      height: 25
      obstacles:
        - {'x':5,'y':5}
        - {'x':8,'y':4}
        - {'x':78,'y':12}
        - {'x':33,'y':14}
        - {'x':7,'y':19}
        - {'x':23,'y':23}
        - {'x':41,'y':11}
        - {'x':44,'y':12}
        - {'x':44,'y':13}
        - {'x':45,'y':14}
        - {'x':45,'y':15}
        - {'x':46,'y':16}

    JUPITER:
      name: Jupiter
      length: 15
      height: 15
      obstacles:
        - {'x':5,'y':5}

    EARTH:
      name: Earth
      length: 3
      height: 3
      obstacles:
        - {'x':1,'y':1}
        - {'x':2,'y':1}
